---
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if not .Values.skipLabels }}
  labels:
    {{- include "gadget.labels" . | nindent 4 }}
  {{- end }}
  name: {{ include "gadget.fullname" . }}
  namespace: {{ include "gadget.namespace" . }}
data:
    config.yaml: |-
      hook-mode: {{ .Values.config.hookMode }}
      fallback-pod-informer: {{ .Values.config.fallbackPodInformer }}
      events-buffer-length: {{ .Values.config.eventsBufferLength }}
      containerd-socketpath: {{ .Values.config.containerdSocketPath }}
      crio-socketpath: {{ .Values.config.crioSocketPath }}
      docker-socketpath: {{ .Values.config.dockerSocketPath }}
      podman-socketpath: {{ .Values.config.podmanSocketPath }}
      operator:
        oci:
          verify-image: {{ .Values.config.verifyGadgets }}
          public-keys:{{ toYaml $.Values.config.gadgetsPublicKeys | nindent 12 }}
          allowed-gadgets:{{ toYaml .Values.config.allowedGadgets | nindent 12 }}
          disallow-pulling: {{ .Values.config.disallowGadgetsPulling }}
      {{- if .Values.config.otelMetricsListen }}
        otel-metrics:
            otel-metrics-listen: {{ .Values.config.otelMetricsListen }}
            otel-metrics-listen-address: {{ .Values.config.otelMetricsAddress }}
      {{- end }}
