services:
  ig:
    image: ${DESKTOP_PLUGIN_IMAGE}
    privileged: true
    network_mode: host
    userns_mode: host
    pid: host
    volumes:
      - /:/host
    environment:
      HOST_ROOT: /host

