# Default values for gadget.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Skip Helm labels
skipLabels: true

# -- Labels to be added to all other resources.
additionalLabels:
  labels: {}

config:
  # -- How to get containers start/stop notifications (auto, crio, podinformer, nri, fanotify, fanotify+ebpf")
  hookMode: auto

  # -- Whether to use the fallback pod informer
  fallbackPodInformer: true

  # -- Containerd CRI Unix socket path
  containerdSocketPath: "/run/containerd/containerd.sock"
  # -- CRI-O CRI Unix socket path
  crioSocketPath: "/run/crio/crio.sock"
  # -- Docker Engine API Unix socket path
  dockerSocketPath: "/run/docker.sock"

  # -- Enable experimental features
  experimental: false

  # -- Events buffer length. A low value could impact horizontal scaling.
  eventsBufferLength: "16384"

image:
  # -- Container repository for the container image
  repository: ghcr.io/inspektor-gadget/inspektor-gadget
  # -- Pull policy for the container image
  pullPolicy: Always
   # -- Tag for the container image
  tag: ""

# -- Node selector used by `gadget` container
nodeSelector:
  kubernetes.io/os: linux

# -- Affinity used by `gadget` container
affinity: {}

# -- Capabilities used by `gadget` container
capabilities: {}

# -- Tolerations used by `gadget` container
tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
