# Default values for gadget.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Inspektor Gadget configuration.
config:
  # -- Containerd CRI Unix socket path
  containerdSocketPath: "/run/containerd/containerd.sock"
  # -- CRI-O CRI Unix socket path
  crioSocketPath: "/run/crio/crio.sock"
  # -- Docker Engine API Unix socket path
  dockerSocketPath: "/run/docker.sock"
  # -- Podman API Unix socket path
  podmanSocketPath: "/run/podman/podman.sock"

  # -- Enable experimental features
  experimental: false

  # -- Events buffer length. A low value could impact horizontal scaling.
  eventsBufferLength: "16384"

  # -- Daemon Log Level. Valid values are: "trace", "debug", "info", "warning", "error", "fatal", "panic"
  daemonLogLevel: "info"

  # -- Namespace where Inspektor Gadget is running
  gadgetNamespace: "gadget"

  # -- Operator configuration, this will only be used if deprecated values are not set.
  operator:
    kubemanager:
      # -- Whether to use the fallback to pod informer
      fallback-podinformer: true
      # -- How to get containers start/stop notifications. Valid values are: "auto", "crio", "podinformer", "nri", "fanotify+ebpf"
      hook-mode: "auto"
    oci:
      verify-image: true
      public-keys:
        - |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoDOC0gYSxZTopenGmX3ZFvQ1DSfh
          Ir4EKRt5jC+mXaJ7c7J+oREskYMn/SfZdRHNSOjLTZUMDm60zpXGhkFecg==
          -----END PUBLIC KEY-----
      allowed-gadgets: []
      disallow-pulling: false
      insecure-registries: []
    otel-metrics:
      otel-metrics-listen: false
      otel-metrics-listen-address: "0.0.0.0:2224"

# -- All configurations below are specific to Kubernetes resources created by the gadget chart.
image:
  # -- Container repository for the container image
  repository: ghcr.io/inspektor-gadget/inspektor-gadget
  # -- Pull policy for the container image
  pullPolicy: Always
  # -- Tag for the container image
  tag: ""
  # -- Pull secrets for the daemonset image
  pullSecrets: []

# -- Node selector used by `gadget` container
nodeSelector:
  kubernetes.io/os: linux

# -- Affinity used by `gadget` container
affinity: {}

# -- Capabilities used by `gadget` container
capabilities: {}

# -- Tolerations used by `gadget` container
tolerations: {}

# -- Skip Helm labels
skipLabels: false

# -- Labels to be added to all other resources.
additionalLabels:
  labels: {}

# -- RuntimeClassName used by daemonset
runtimeClassName: ""

# -- Mount pull secret (gadget-pull-secret) to pull image-based gadgets from private registry
mountPullSecret: false

# -- Set AppArmor profile.
appArmorProfile: "unconfined"

# -- Additional environment variables to add to the gadget container
additionalEnv: []
  # - name: EXAMPLE_VAR
  #   value: "example_value"
  # - name: EXAMPLE_SECRET_VAR
  #   valueFrom:
  #     secretKeyRef:
  #       name: secret-name
  #       key: secret-key
